nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: []
    allow_headers: []
    allow_methods: []
    expose_headers: []
    max_age: 0
    hosts: []
    origin_regex: true
    forced_allow_origin_value: ~
    skip_same_as_origin: true

  paths:
    "^/api/":
      allow_origin: [
          "http://localhost:5173",
          # "https://cfcassola.stoplight.io",
          "http://127.0.0.1:5173",
        ]
      allow_headers: ["Content-Type", "Authorization", "Origin", "Accept"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
      max_age: 3600
